### ISSUE TITLE
Support protocol agnostic matching

### ISSUE THREAD

**Issue by adentify** [requestly/requestly.github.io#3]
Hi. Am a big fan of this plugin and have been proselytising it to whoever listens to me.

One thing that would improve efficiency would be to make the matching of urls agnostic to the protocol eg;
![image](https://cloud.githubusercontent.com/assets/1849728/20757063/d64f4566-b70c-11e6-9225-a7e34b2208fb.png)

Otherwise two rules need to be created to match HTTP and HTTPS whereas a protocol agnostic version would only require one.

**Comment by sachinjain024** [comment]
Thanks @adentify. I really appreciate that you highlighted an improvement area. One of the next features I will work on is adding wildcard (*) support in as an operator.

Once this change is rolled out, you should be able to setup your rule like this:

    Url contains *//<your_url>
    Destination $1//<your_url>

Each * will be replaced with $1, $2 and so on. Let me know if you see any problem with this approach.

BTW I have created a new repository for such discussions and raising github issues.
https://github.com/requestly/requestly-issues/issues

Please star that for any further communication on the issues and logging a new one.

**Comment by sachinjain024** [comment]
@adentify This change has been implemented and released in extension v4.2.6. I have uploaded the new build to chrome store and you should get this in an hour or so.

Please follow these steps:

1. Select Rule Operator: Matches (wildcard)
2. Your rule becomes

    Url Matches (Wildcard) *://<your_url>
    Destination $1//<your_url>

Let me know if it solves your issue. Thanks once again for reporting it.

**Comment by sachinjain024** [comment]
Have not heard back from OP so closing this issue.
